#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
reset=`tput sgr0`

echo "${yellow}Install 'yay' & Update current system${reset}"

sudo pacman -S yay pamac --noconfirm
sudo pacman -Syyu --noconfirm
yay -Syyua --noconfirm


